name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpstan@v3
        with:
          path: src/

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_version: 7.4
